---

networks:
  redisnet:
    driver: bridge

volumes:
  redisinsight-data:

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "63799:6379"
    networks:
      - redisnet

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8111:8001"
    volumes:
      - redisinsight-data:/db
    networks:
      - redisnet




